#!/usr/local/bin/python
# -*- coding: utf-8 -*-
import sys

if "/app" not in sys.path:
        sys.path.append("/app")

from finance_ml.scripts.yfinance.update_quarterly_db import update_quarterly_database

if __name__ == '__main__':
    ticker_symbols = sys.argv[1:] if len(sys.argv) > 1 else None

    sys.exit(update_quarterly_database(ticker_symbols))
